config/routes.rb
Rails.application.routes.draw do
  get 'persons/index'

  resources :persons do
    collection do
      get 'halloffame'
      get 'pgpguide'
    end
  end

  get 'halloffame' => 'persons#halloffame', as: :halloffame
  get 'pgpguide' => 'persons#pgpguide', as: :pgpguide

  root 'persons#index'

end

app/models/key.rb
class Key < ActiveRecord::Base
	belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :keys, dependent: :destroy

	before_create :send_verification_email

	# This method creates a random verification hash, checks that the hash is unique in the database,
	# then sends the verification email. Mode is either 'http' or 'https'
	def send_verification_email(person = self, website_protocol = 'https://')

		website_regex = /^(http\:\/\/|https\:\/\/)?([a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,63})(\/\S*)?$/
		exists = true
		# Generates a random, unique hash for every person
		begin
		  random_hash = SecureRandom.hex(16)
		  if Person.exists?(:confirm_hash => random_hash)
		    exists = true
		  else
		    person.confirm_hash = random_hash
		    exists = false
		  end
		end while exists === true


		# Get the website protocol from the URL
		passed_website_protocol = website_regex.match(person.url)[1]

		# If the URL had a website protocol
		if (defined?passed_website_protocol).nil?
			# Use that one
			website_protocol = passed_website_protocol
		end

		# Get actual URL part, i.e. 'pgpasc.org' in 'http://pgpasc.org/halloffame.html'
		website = website_regex.match(person.url)

		# If the website was wrongly formatted
		if website == nil
			return false
		else
			# Otherwise get the URL
			website = website_regex.match(person.url)[2]
		end
		# Set the current persons URL to that
		person.url = website

		# If a person with that URL already exists, and they are confirmed show an error
		if Person.exists?(:url => website)
			existing_person = Person.find_by url: website
			if existing_person.confirmed == true
				return false
			end
		end

		# Put together website for CURL request
		website = website_protocol + website + '/pgp.asc'

		# Get the key with a CURL request
		begin
			request = Curl::Easy.new(website)
			request.ssl_verify_peer = false
			request.perform
		rescue Curl::Err::SSLPeerCertificateError, Curl::Err::HostResolutionError, Curl::Err::ConnectionFailedError => error
			# If it failed with HTTPS, try HTTP
			if website_protocol == 'https://'
				return send_verification_email(person, 'http://')
			end
			# If the request fails with HTTPS and with HTTP, flash an error message
			return false
		end
		# Slice the key from the HTML
		key = request.body_str
	  # Import the key
		imported_key = GPGME::Key.import(key)
		# Send the email
		PersonMailer.verification_email(person, key).deliver_now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  require 'securerandom'

  def index
  	@person = Person.new

    # If a confirm hash parameter is passed
    if params[:ch] != nil
      # And a person with that confirm hash exists
      if Person.exists?(:confirm_hash => params[:ch])
        # Find the person and set 'confirmed' to true
        person = Person.find_by confirm_hash: params[:ch]
        person.update_attribute(:confirmed, true)
        # The show a success message
        flash[:success] = "You are now in the Hall of Fame, welcome!"
      else
        # Otherwise show an error
        flash[:error] = "Something went wrong with the verification, please try again!"
      end
      redirect_to root_path
    end
  end

  def create
    @person = Person.create(person_params)

    # If nothing went wrong with the sending of the mail
    if @person.save
      flash[:success] = "Almost there, check your inbox!"
    else
      # This gets shown when something went wrong in the model
      flash[:error] = "Something went wrong, did you enter the right URL?"
    end

  	redirect_to root_path
  end

  def show
    redirect_to root_path
  end

  def halloffame
    @person = Person.new
    @persons = Person.all.where(confirmed: 'true').order('updated_at DESC')
  end

  def pgpguide
    @person = Person.new
  end

  private
    def person_params
      params.require(:person).permit(:name, :url, :mail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>pgp.asc</title>
  <meta name="description" content="pgp.asc is an initiative to decentralize public PGP keys, making it easier to get an up to date and authenticated key.">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" href="assets/icon_maze_key.ico">


  <link rel="stylesheet" href="assets/application.css">
  <link href='https://fonts.googleapis.com/css?family=Merriweather|Open+Sans:600italic,300' rel='stylesheet' type='text/css'>
  <script src="assets/application.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><h3><%= value %></h3></div>
  <% end %>

  <%= yield %>

  <!-- Footer -->
  <section class="footer">
    <div class="wrapper">
      <div class="footer__section">
        <h4 class="footer__heading">Are you using pgp.asc?</h4>
        <p class="footer__text">Awesome! Submit your site below:</p>
        <!-- Form -->
        <%= form_for @person, url: persons_path, html: {class: "footer__form"} do |f| %>
          <%= f.text_field :name, class: "footer__form--input", placeholder: "Your name" %>
          <%= f.text_field :url, class: "footer__form--input", placeholder: "Your website" %>
          <%= f.text_field :mail, class: "footer__form--input", placeholder: "Your email", type: 'email' %>
          <%= f.submit "", class: "footer__form--submit-button", type: "image", src: "assets/button_submit.png" %>
        <% end %>
        <!-- End of Form -->
      </div>
      <div class="footer__section footer__section--social">
        <h4 class="footer_heading">Social Links</h4>
        <a href="https://github.com/mstoiber/pgp.asc" onclick="OWATracker.trackAction('social', 'click', 'github');"><div class="social__github"></div></a>
        <a href="https://twitter.com/mxstbr" onclick="OWATracker.trackAction('social', 'click', 'twitter');"><div class="social__twitter"></div></a>
        <a href="https://www.facebook.com/pgp.asc" onclick="OWATracker.trackAction('social', 'click', 'facebook');"><div class="social__fb"></div></a>
      </div>
      <div class="footer__section footer__section--contribute">
        <h4 class="footer__heading">Contribute</h4>
        <p class="footer__text">Head over to <a href="https://github.com/mxstbr/pgp.asc" onclick="OWATracker.trackAction('footer', 'click', 'github');">GitHub</a> to join the discussion!</p>
      </div>
    </div>
  </section>

  <!-- Start Open Web Analytics Tracker -->
  <script type="text/javascript">
  //<![CDATA[
  var owa_baseUrl = 'http://analytics.mxstbr.com/';
  var owa_cmds = owa_cmds || [];
  owa_cmds.push(['setSiteId', '4a7d8a01d9d8ddb8d8d43b48e835da7a']);
  owa_cmds.push(['trackPageView']);
  owa_cmds.push(['trackClicks']);
  owa_cmds.push(['trackDomStream']);

  (function() {
    var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
    owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
    _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
    var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
  }());
  //]]>
  </script>
  <!-- End Open Web Analytics Code -->
</body>
</html>

app/views/persons/_nav.html.erb
<!-- Navigation -->
<a href="<%= root_path %>" id="icon">
	<img src="assets/icon_maze_key.svg" alt="pgp.asc logo"></img>
</a>
<nav class="clearfix">
	<ul class="nav clearfix">
		<%= nav_link_to root_path, {:class => 'nav__item'}, {:selected_class => 'nav__item--active'} do %>
			<li>Home</li>
		<% end %>
		<%= nav_link_to halloffame_path, {:class => 'nav__item'}, {:selected_class => 'nav__item--active'} do %>
			<li>Hall of Fame</li>
		<% end %>
		<%= nav_link_to pgpguide_path, {:class => 'nav__item'}, {:selected_class => 'nav__item--active'} do %>
			<li>PGP Guide</li>
		<% end %>
	</ul>
	<div id="hamburger" onclick='showMenu()'></div>
</nav>
<!-- End of Navigation -->

app/views/persons/halloffame.html.erb
<%= render 'nav' %>

<!-- Content -->
<section class="content content--long" id="content">
	<h1>Hall of Fame</h1>
	<p>To get into the Hall of Fame, submit your details below:</p>	
	<!-- Form -->
	<%= form_for @person, url: persons_path, html: {class: "halloffame__form"} do |f| %>
	  <%= f.text_field :name, class: "halloffame__form--input", placeholder: "Your name" %>
	  <%= f.text_field :url, class: "halloffame__form--input", placeholder: "Your website" %>
	  <%= f.text_field :mail, class: "halloffame__form--input", placeholder: "Your email" %>
	  <%= f.submit "", class: "halloffame__form--submit-button", type: "image", src: "assets/button_submit.png" %>
	<% end %>
	<!-- End of Form -->
	<ul class="halloffame__person-list">
		<% @persons.each do |person| %>
			<li class="halloffame__person"><%= person.name %> - <a href="http://<%= person.url %>"><%= person.url %></a></li>
		<% end %>
	</ul>
</section>
<!-- End of Content -->

app/views/persons/index.html.erb
<script>
	$(function() {
		// Check if animation has played before, and don't show it if it has
		if (localStorage.getItem('animation') !== 'played') {
			// Hide elements that get faded in
			$('.header__logo').css('opacity', '0');
			$('nav').css('opacity', '0');
			$('#icon img').css('opacity', '0');
			$('.header__heading').css('opacity', '0');
			$('.header__subheading').css('opacity', '0');
			$('.header__arrow').css('opacity', '0');

			setTimeout(function() {
				// Fade logo in
				$('.header__logo').css('transition', 'opacity 250ms');
				$('.header__logo').css('opacity', '1');
				setTimeout(function() {
					// Fade header elements in and add transition to elements that fade in
					$('nav').css('transition', 'opacity 250ms');
					$('#icon img').css('transition', 'opacity 250ms');
					$('.header__heading').css('transition', 'opacity 250ms');
					$('.header__subheading').css('transition', 'opacity 250ms');
					$('.header__arrow').css('transition', 'opacity 250ms');
					// Fade heading and subheading in
					$('.header__heading').css('opacity', '1');
					setTimeout(function() {
						$('.header__subheading').css('opacity', '1');
						// Fade nav and arrow in
						setTimeout(function() {
							$('nav').css('opacity', '1');
							$('#icon img').css('opacity', '1');
							$('.header__arrow').css('opacity', '1');
						}, 600);
					}, 150);
				}, 300);
			}, 150);
			// Set animation value in localStorage for the next time the person opens the page
			localStorage.setItem("animation", "played");
		}
	});
</script>

<!-- Header -->
<section class="header">
	<%= render 'nav' %>
	<div class="header__main">
		<%= inline_svg "icon_maze_key.svg", class: "header__logo", id: "logo" %>
		<h1 class="header__heading">pgp.asc</h1>
		<h2 class="header__subheading">Decentralize public PGP keys</h2>
	</div>

	<a href="#content" class="header__arrow"><img src="/assets/button_further.svg" class="header__arrow"></img></a>
</section>
<!-- End of Header -->

<!-- Content -->
<section class="content" id="content">
	<div class="content__section group">
		<img src="/assets/icon_maze_key.svg" alt="Hexagonal Maze with a key in the middle" class="content__hex"></img>
		<h3 class="content__heading">What is pgp.asc?</h3>
		<p class="content__text">pgp.asc is an initiative to decentralize public PGP keys, making it easier to get an up to date and authenticated key.</p>
		<p class="content__text">Sounds complicated? It isn’t: Just upload your public PGP key to your websites root folder and you’re good to go!</p>
	</div>
	<div class="content__section group">
		<img src="/assets/icon_maze_folder.svg" alt="Hexagonal Maze with a folder in the middle" class="content__hex"></img>
		<h3 class="content__heading">How and where?</h3>
		<p class="content__text">Simply put your public key in a file called pgp.asc in the root of your server. That way people can find your PGP key by going to https://url.com/pgp.asc.</p>
		<p class="content__text">This takes less time than to search in a public key server, and absolutely guarantees authenticity.</p>
	</div>
	<div class="content__section group">
		<img src="/assets/icon_maze_question.svg" alt="Hexagonal Maze with a question mark in the middle" class="content__hex"></img>
		<h3 class="content__heading">Why should I?</h3>
		<p class="content__text">To make it easier to find your public PGP key, and validate it. (Since only you have access to your server) To provide an up to date key, as you can delete your old one. To spread the word about encryption.</p>
	</div>
</section>
<!-- End of Content -->